name: selenium-github-actions
on: [push]
jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: |
          pip install --upgrade pip
          pip install get-chrome-driver --upgrade
          pip install -r selenium/requirements.txt
          python selenium/main.py
