name: selenium-github-actions
on: [push]
jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: pip setting
        run: |
          pip install --upgrade pip
          pip install get-chrome-driver --upgrade
          pip install -r selenium/requirements.txt
      - name: scraping
        working-directory: selenium
        run: |
          python main.py
          mv README.md ./../README.md　# README.mdを上書き
      - name: commit files
        run: | # githubの設定
          git config --global user.name "${{ github.ACTOR }}"
          git config --global user.email "${{ github.EMAIL }}"
          git add README.md
          git commit -m 'update README.md'
          git push origin main # mainブランチにプッシュ
          

